version: 0.0
os: linux
files:
  - source: / 
    destination: /var/www/html/
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
  AfterInstall:
    - location: after_install.sh
      timeout: 300
  ApplicationStart:
    - location: application_start.sh
      timeout: 300
