version: 0.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:eu-central-1:054037131762:task-definition/Task:8"
        loadBalancerInfo:
          ContainerName: "New"
          ContainerPort: 80
