version: 0.0
- myECSService:
      type: AWS::ECS::Service
      properties:
        clusterName: New-Cluster1
        serviceName: New2
        desiredCount: 1
        taskDefinition: Task
hooks:
  BeforeInstall:
    - location: before_install.sh
      timeout: 300
  AfterInstall:
    - location: after_install.sh
      timeout: 300
  ApplicationStart:
    - location: application_start.sh
      timeout: 300
