version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR....
      - aws ecr get-login-password --region eu-central-1 | docker login --username AWS --password-stdin 054037131762.dkr.ecr.eu-central-1.amazonaws.com
      - REPOSITORY_URI=054037131762.dkr.ecr.eu-central-1.amazonaws.com/project/newregistryecr
      - IMAGE_TAG=$CODEBUILD_RESOLVED_SOURCE_VERSION
  build:
    commands:
      - echo Building the Docker image...
      - docker build --no-cache -t $REPOSITORY_URI:latest .
      - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
  post_build:
    commands:
      - echo Generating imagedefinitions.json...
      - docker push $REPOSITORY_URI:latest
      - docker push $REPOSITORY_URI:$IMAGE_TAG
      - echo "Updating task definition JSON with the new image..."
      - sed -i 's@CONTAINER_IMAGE@'"$REPOSITORY_URI"'@' taskdef.json
      # Register a new task definition
      - echo "Registering new ECS task definition..."
      - TASK_DEF_ARN=$(aws ecs register-task-definition --family TASK --cli-input-json file://taskdef.json --region eu-central-1 --query 'taskDefinition.taskDefinitionArn' --output text)
      - LATEST_TASK_DEF=$(aws ecs list-task-definitions --family-prefix  TASK --sort DESC --query 'taskDefinitionArns[0]' --output text)
      - echo "Latest Task Definition = $LATEST_TASK_DEF"
      - sed -i 's@LATEST_TASK_DEF @'"$LATEST_TASK_DEF"'@' appspec.yaml
      - printf '{"ImageURI":"%s"}' $REPOSITORY_URI:$IMAGE_TAG > imageDetail.json 
      
artifacts:
    files:
    - imageDetail.json
    - appspec.yml
